#!/usr/bin/env python

import os.path, imghdr, random, sys

def get_random_image(path='.'):
    wpfile = ''
    if os.path.isfile(path):
        wpfile = '' if imghdr.what(os.path.realpath(path)) is None else os.path.realpath(path)
    elif os.path.isdir(path):
        wppath = os.path.realpath(path)
    else:
        wppath = os.getcwd()
    
    poss_files = os.listdir(wppath)
    poss_index_tries = set()
    
    while len(wpfile) == 0:
        indx = random.randint(-1, len(poss_files) - 1)
    
        if indx not in poss_index_tries:
            poss_index_tries.add(indx)
            wpfile = os.path.join(wppath, poss_files[indx])
            if not os.path.isfile(wpfile) or imghdr.what(wpfile) is None:
                wpfile = ''
    
        if len(wpfile) == 0 and len(poss_index_tries) == len(poss_files):
            break

    return wpfile

def main():
    filename = get_random_image() if len(sys.argv) < 2 else get_random_image(sys.argv[1])
    print(filename)

if __name__ == "__main__":
    main()

