#!/bin/bash

#
# Copied from https://mutelight.org/practical-tmux and modified
# to create a default session since my standard M.O. is to only
# have a single terminal open at any given time.  If/when this
# changes, I will likely implement the session id methodology
# that is in the original; until then, there is no need to
# complicate this script.
#

#
# Modified TMUX start script from:
#     http://forums.gentoo.org/viewtopic-t-836006-start-0.html
#
# Store it to `~/bin/tmx` and issue `chmod +x`.
#

# Works because bash automatically trims by assigning to variables and by
# passing arguments
trim() { echo $1; }

base_session="$1"
if [[ -z "$base_session" ]]; then
    base_session="Main"
fi

# Only because I often issue `ls` to this script by accident
if [[ "$1" == "ls" ]]; then
    tmux ls
    exit
fi

# This actually works without the trim() on all systems except OSX
tmux_nb=$(trim `tmux ls | grep "^$base_session" | wc -l`)
if [[ "$tmux_nb" == "0" ]]; then
    echo "Launching tmux base session $base_session ..."
    tmux new-session -s $base_session
else
    # Make sure we are not already in a tmux session
    if [[ -z "$TMUX" ]]; then
        echo "Attaching to base session $base_session ..."
        # Attach to the session
        tmux attach-session -t $base_session
    fi
fi
