#!/bin/bash

#
# Copied from https://mutelight.org/practical-tmux and modified
# to create a default session since my standard M.O. is to only
# have a single terminal open at any given time.  If/when this
# changes, I will likely implement the session id methodology
# that is in the original; until then, there is no need to
# complicate this script.
#

#
# Modified TMUX start script from:
#     http://forums.gentoo.org/viewtopic-t-836006-start-0.html
#
# Store it to `~/bin/tmx` and issue `chmod +x`.
#

# Works because bash automatically trims by assigning to variables and by
# passing arguments

TMUX_COMMAND="/usr/bin/tmux"
MC_COMMAND="/usr/lib/mc/mc-wrapper.sh"
base_session="$1"

# Set the default session name if  one was not passed in
if test -z "${base_session}" ; then
    base_session="Main"
fi

# Only because I often issue `ls` to this script by accident
if [[ "${base_session}" == "ls" ]]; then
    ${TMUX_COMMAND} ls
    return
fi

test -z "${TMUX}" || return

${TMUX_COMMAND} has-session -t ${base_session}
running=$?

[ "${running}" -eq "1" ] && \
    ${TMUX_COMMAND} new-session -d -s ${base_session} ${SHELL} \; new-window -d -t ${base_session} -n MC ${MC_COMMAND}

${TMUX_COMMAND} new-session -A -s ${base_session}
