#!/usr/bin/bash

RUNNAME="WoW"
LOGDIR="${HOME}/wine-logs"
LOG="${LOGDIR}/${RUNNAME}-$(date "+%Y%m%d%H%M%S").log"

[[ -d ${LOGDIR} ]] || mkdir -p ${LOGDIR}

export force_s3tc_enable=true

setarch i386 -3 -L -B -R wine "C:\\Program Files (x86)\\World of Warcraft\\Wow.exe" > ${LOG} 2>&1
